services:
  gateway:
    ports:
      - "8787"

  flash-sale:
    ports:
      - "80"

  iot-realtime:
    ports:
      - "80"

  ros2-bridge:
    ports:
      - "80"

  user-module-demo:
    ports:
      - "80"
