services:
  gateway:
    ports:
      - "8787"

  ros2-backend:
    ports:
      - "8080"

  examples-portal:
    ports:
      - "80"

  flash-sale:
    ports:
      - "80"

  blog:
    ports:
      - "80"

  iot-realtime:
    ports:
      - "80"

  ros2-bridge:
    ports:
      - "80"

  user-module-demo:
    ports:
      - "80"
